### PR TITLE
Add new font ROM from ND320 rev 24

### PR DESCRIPTION
**Pull request by Frodevan**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
How about firmware ROM?

**Comment by Frodevan** [comment]
You can find the rest of the firmware here: https://github.com/Frodevan/Tandberg/tree/main/TDV-2200/ROM%20Files/TDV-2200S%20Base%20Unit%20TDV-2200-9S

**Comment by larsbrinkhoff** [comment]
Looks great, thanks!

**Comment by sebras** [comment]
@Frodevan sorry for the extremely long time to merging this. I was busy when you sent it and then I simply forgot. but today it popped up on my github page, so I decided to _finally_ do something about it. :)

**Pull request merged**
